<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "we_dam2fal62"
 *
 * Auto generated by Extension Builder 2014-06-27
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'DAM2FAL 6.2',
	'description' => 'This extension migrates your Dam-data into FAL.',
	'category' => 'module',
	'author' => 'Daniel Hasse - websedit AG',
	'author_email' => 'extensions@websedit.de',
	'author_company' => 'websedit AG',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.1',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.2.0-6.2.99',
			'fluid' => '6.2.0-6.2.99',
			'typo3' => '6.2.3-6.2.99',
			'filemetadata' => '6.2.0-6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);